### ISSUE TITLE
Documentation is wrong/unclear

### ISSUE THREAD

**Issue by stephanrenggli** [bitnami/bitnami-docker-keycloak-gatekeeper#1]
Hi there, just tried to set this up and struggled for some time due to the documentation being wrong/unclear.

In your configuration examples you always work with `bitnami/keycloak-gatekeeper:latest`.
According to the dockerfile `latest` is based on `scratch` which doesn't have the entrypoint `/run.sh`. The volume mounting obviously doesn't work either while on the `latest` branch.

I don't know if latest is supposed to be based on scratch, but I think the documentation should be updated to reflect the correct options for each branch.

After switching to `bitnami/keycloak-gatekeeper:2.3.0-debian-9-r2` the documentation provided worked (specifying the parameters via docker-compose command).

**Comment by juan131** [comment]
Hi @stephanrenggli 

Thanks for reporting the issue! You're right, the docs are outdated.

We moved this image to a "scratch" approach to make it as slim as possible and, we didn't update the https://github.com/bitnami/bitnami-docker-keycloak-gatekeeper#using-command-line-options section.

I just create a PR to update it!

Thanks so much much!
