### ISSUE TITLE
Documentation incorrect, container does not start

### ISSUE THREAD

**Issue by migmartri** [bitnami/bitnami-docker-keycloak-gatekeeper#5]
In the TLDR you can read:

```
$ docker run --rm --name keycloak-gatekeeper bitnami/keycloak-gatekeeper:2 keycloak-proxy --help
```

the result of that command is 

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"keycloak-proxy\": executable file not found in $PATH": unknown.
```

**Comment by migmartri** [comment]
The issue seems to be that `keycloak-proxy` is not in the PATH but in the root `/keycloak-proxy`

**Comment by alemorcuq** [comment]
Hi, @migmartri.

This looks like a mistake on our part. The command should be:

```bash
$ docker run --rm --name keycloak-gatekeeper bitnami/keycloak-gatekeeper:2 /keycloak-proxy --help
```

We will fix it, thank you for reporting this.

**Comment by alemorcuq** [comment]
Hi, @migmartri.

The documentation has been updated to reflect the correct command. Thank you very much for reporting this.

**Comment by Stankye** [comment]
New release is /keycloak-gatekeeper instead of /keycloak-proxy

**Comment by dani8art** [comment]
Hi @Stankye, thank you so much for reporting this. I updated the README.md and now you can execute the TL;RD command. 

```
docker run --rm --name keycloak-gatekeeper bitnami/keycloak-gatekeeper:latest /keycloak-gatekeeper --help
```

Regards.
