### ISSUE TITLE
Update to newest keycloak-gatekeeper release 8.0.1

### ISSUE THREAD

**Issue by phxql** [bitnami/bitnami-docker-keycloak-gatekeeper#6]
Hello,

first, thanks for your work!

Could you please update the Keycloak Gatekeeper Image to use Keycloak Gatekeeper 8.0.1 (see [here](https://github.com/keycloak/keycloak-gatekeeper/releases/tag/8.0.1))?

Thanks!

**Comment by phxql** [comment]
I contributed a pr: #7

**Comment by juan131** [comment]
Hi @phxql 

Thanks for opening the issue! I'll take look to your PR

**Comment by juan131** [comment]
I'm closing the issue since we already updated this image to the latest release (**8.0.1**). Thanks again for reporting the issue with the versions @phxql

**Comment by phxql** [comment]
Thanks for your work!
